//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agenda3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int Id { get; set; }
        public string Evento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Lugar { get; set; }
        public int ModelFirstId { get; set; }
        public int ModelFirstId1 { get; set; }
    
        public virtual ModelFirst Navegacion { get; set; }
    }
}
